resolver: lts-11.22
tested-with: GHC == 8.2.2
flags: {}
packages:
- detour-via-sci
- detour-via-uom
- clip
- cmd
- comp
- earth
- fsdb
- gap
- igc
- kml
- latlng
- lookup
- mask
- route
- scribe
- siggy-chardust
- span
- task
- tasty-compare
- time
- track
- units
- zone
- flare-timing
- app-serve
extra-deps:
- hxt-xpath-9.1.2.2
- uom-plugin-0.3.0.0
- doctest-0.15.0
- megaparsec-7.0.4
- parser-combinators-1.0.0
- git: https://github.com/blockscope/hcoord.git
  commit: 3c3859dac5da111e57a6de09764ffdb127197c4a
  subdirs:
  - hcoord
  - hcoord-utm
