name: cabal

on:
  push:
    branches: [ master, fix/test-suite-score-393 ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["2.4"]
        ghc:
          - "8.2.2"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-haskell@v1
      name: Setup GHC and Cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v1
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    - name: Build
      run: |
        cabal v2-update
        cabal v2-build all

    - name: Unit and property tests
      run: |
        cabal v2-test all
