name: Continuous Integration

on:
  pull_request: { "branches": [ "master" ] }
  push: { "branches": [ "master", "fix/test-suite-score-393" ] }

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: 💽 Install OS Packages
      uses: mstksg/get-package@v1
      with:
        apt-get: libgmp-dev

    - name: 📥 Checkout repository
      uses: actions/checkout@v1

    - name: 🧰 Setup Stack
      uses: mstksg/setup-stack@v1

    - name: 🔨 Build & Test
      run: |
        stack test --no-terminal
