name: pier

on:
  push:
    branches: [ci-pier]
  pull_request:
    branches: [master]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal:
          - "3.2"
        ghc:
          - "8.2.2"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-haskell@v1.1
      name: setup GHC and cabal-install
      with:
        enable-stack: true
        stack-version: latest
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    # SEE: https://github.com/actions/cache/blob/master/examples.md#haskell---cabal
    - uses: actions/cache@v1
      name: cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - uses: actions/cache@v1
      name: cache .stack-work
      with:
        path: .stack-work
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack-work

    - uses: actions/cache@v1
      name: cache ~/.pier/artifact
      with:
        path: ~/.pier/artifact
        key: ${{ runner.os }}-${{ matrix.ghc }}-shared-pier-artifact

    - uses: actions/cache@v1
      name: cache _pier/artifact
      with:
        path: _pier/artifact
        key: ${{ runner.os }}-${{ matrix.ghc }}-pier-artifact

    - uses: actions/cache@v1
      name: cache-pier-exe
      with:
        path: ~/.local/bin/pier
        key: ${{ runner.os }}-${{ matrix.ghc }}-pier-exe

    - name: install pier
      if: steps.cache-pier-exe.outputs.cache-hit != 'true'
      run: stack install pier --stack-yaml=lang-haskell/stack-pier.yaml

    - name: siggy-chardust
      run: ~/.local/bin/pier test siggy-chardust:test:digits
