name: stack

on:
  push:
    branches: [main, ci-stack]
  pull_request:
    branches: [main]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.10"]
        ghc:
          - "8.2"

    steps:
    - uses: mstksg/get-package@v1
      name: Install OS Packages
      with:
        apt-get: libgmp-dev

    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: haskell-actions/setup@v2
      name: Setup stack and cabal-install
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
        enable-stack: true

    - name: Cache Key
      id: cache_key
      run: echo ::set-output name=key::$(md5sum lang-haskell/stack.yaml | awk '{print $1}')

    - uses: actions/cache@v1
      name: Cache ~/.stack
      id: cache
      with:
        path: ~/.stack
        key: ${{ matrix.os }}-${{ steps.cache_key.outputs.key }}

    # - name: build tests
    #   run: stack test --no-run-tests --no-terminal

    - name: detour-via-sci:doctest
      run: stack test detour-via-sci:doctest --no-terminal --test-arguments "--color=always"

    # compile error, Not in scope: 'u'
    # - name: detour-via-uom:doctest
    #   run: stack test detour-via-uom:doctest --no-terminal --test-arguments "--color=always"

    # on github runner: Examples: 247  Tried: 212  Errors: 0  Failures: 4
    # on mac locally: Examples: 247  Tried: 247  Errors: 0  Failures: 0
    # - name: flight-earth:doctest
    #   run: stack test flight-earth:doctest --no-terminal --test-arguments "--color=always"

    - name: flight-earth:geodesy
      run: stack test flight-earth:geodesy --no-terminal --test-arguments "--color=always"

    # 81 out of 222 tests failed
    # - name: flight-earth:forbes
    #   run: stack test flight-earth:forbes --no-terminal --test-arguments "--color=always"

    - name: flight-earth:greda
      run: stack test flight-earth:greda --no-terminal --test-arguments "--color=always"

    - name: flight-earth:greda-r
      run: stack test flight-earth:greda-r --no-terminal --test-arguments "--color=always"

    - name: flight-earth:meridian
      run: stack test flight-earth:meridian --no-terminal --test-arguments "--color=always"

    - name: flight-earth:meridian-r
      run: stack test flight-earth:meridian-r --no-terminal --test-arguments "--color=always"

    - name: flight-earth:published
      run: stack test flight-earth:published --no-terminal --test-arguments "--color=always"

    - name: flight-earth:published-r
      run: stack test flight-earth:published-r --no-terminal --test-arguments "--color=always"

    # compile error
    # - name: flight-earth:zone
    #   run: stack test flight-earth:zone --no-terminal --test-arguments "--color=always"

    # compile error
    # - name: flight-earth:cylinder
    #  run: stack test flight-earth:cylinder --no-terminal --test-arguments "--color=always"

    # compile error
    # - name: flight-earth:cylinder-r
    #  run: stack test flight-earth:cylinder-r --no-terminal --test-arguments "--color=always"

    - name: siggy-chardust:doctest
      run: stack test siggy-chardust:doctest --no-terminal --test-arguments "--color=always"

    - name: siggy-chardust:digits
      run: stack test siggy-chardust:digits --no-terminal --test-arguments "--color=always"

    # 1 failure
    # - name: flight-track:doctest
    #   run: stack test flight-track:doctest --no-terminal --test-arguments "--color=always"

    - name: flight-units:doctest
      run: stack test flight-units:doctest --no-terminal --test-arguments "--color=always"

    - name: flight-zone:doctest
      run: stack test flight-zone:doctest --no-terminal --test-arguments "--color=always"

    - name: flight-zone:serial
      run: stack test flight-zone:serial --no-terminal --test-arguments "--color=always"
